language: android  
android:
  components:
    - tools
    - build-tools-2.0.2
    - android-25
    - extra-android-m2repository
    - extra-android-support

before_install:
  - chmod +x gradlew

script:  
  - ./gradlew assembleRelease
